### ISSUE TITLE
COCO dataset directory layout

### ISSUE THREAD

**Issue by chrisliu54** [msracver/Relation-Networks-for-Object-Detection#10]
Could you please show us how to arrange COCO dataset's directory layout(including train/val/test)?

I found it different between your specification in **cfg** file and official COCO dataset, e.g. **valminusminival2014** and **minival2014**.

The annotation files I pulled from COCO's official site include `annotations_trainval2014.zip` and `image_info_test2015.zip`. The content inside zip file looks like this for `trainval2014` and `test2015` respectively:
![image](https://user-images.githubusercontent.com/12222396/41694770-7eeeae28-753e-11e8-8175-d8b77e8e5f9a.png)
![image](https://user-images.githubusercontent.com/12222396/41694787-900e32b4-753e-11e8-86fa-3c355f6edef8.png)

Therefore, I got error message like this:
![image](https://user-images.githubusercontent.com/12222396/41694694-1a353588-753e-11e8-8ffa-9b6564cf2cb1.png)

@chengdazhi

**Comment by chengdazhi** [comment]
Hi, you can download all annotation files from: https://1drv.ms/f/s!Aj-v9If_gNq2gVt73yx7GjbwiwB-

All annotation json files go directly under ./data/coco/annotations

All images go under ./data/coco/train2014 and ./data/coco/val2014

**Comment by chrisliu54** [comment]
Sure, thanks!

**Comment by wanghao14** [comment]
@chengdazhi Hi, there is nothing in the shared link now. Could you please update and give an available link of the annotations?

**Comment by chengdazhi** [comment]
@JisuiWang Hi, you can find the annotations files at: https://pan.baidu.com/s/1kUv4fxd_bilGz3L0Zyfjjg 
The password is t64w

**Comment by wanghao14** [comment]
@chengdazhi Thanks a lot!
