### ISSUE TITLE
What does it mean for FIRST_N under TRAIN in the yaml config file?

### ISSUE THREAD

**Issue by Kongsea** [msracver/Relation-Networks-for-Object-Detection#15]
Does it mean to propose first N proposals or first N detections for one image?
Configs in `resnet_v1_101_coco_trainvalminus_rcnn_end2end_relation_learn_nms_8epoch.yaml`.

**Comment by chengdazhi** [comment]
Hi, as most proposals produced by rcnn are background proposals and possess somewhat pessimistic confidence scores, they are a waste of computation in learn nms module, so FIRST_N eliminates them before feeding the proposals into learn nms module. It also eases the learning process. I suggest that you refer to our code for details.

**Comment by Kongsea** [comment]
Thank you.
