### ISSUE TITLE
multi-boxes arise when using resnet_v1_101_coco_trainvalminus_rcnn_dcn_end2end_relation_learn_nms_8epoch model to inference

### ISSUE THREAD

**Issue by huiyang865** [msracver/Relation-Networks-for-Object-Detection#16]
Hi,
I apply the resnet_v1_101_coco_trainvalminus_rcnn_dcn_end2end_relation_learn_nms_8epoch.yaml to train a model. Then using the trained model to inference the test image, I find there are multiple boxes appear on the same object. Do I not train the nms layer thoroughly? So I need to add nms to remove the duplicate boxes.

**Comment by chengdazhi** [comment]
I think multiple boxes on the same object is not that strange, as long as you get your AP right. Are you trying our code on your dataset? In that case, you need to finetune the parameters like first_n.

**Comment by huiyang865** [comment]
Thanks for reply.
What's the meaning of the parameter first_n? Is it used for removing the duplicate boxes? How large should I set first_n?

**Comment by Kongsea** [comment]
Please ref [this](https://github.com/msracver/Relation-Networks-for-Object-Detection/issues/15).

**Comment by chengdazhi** [comment]
@Kongsea First_n indicates how many proposals you want to preserve for each class, I think you should at least make first_n high enough to not lose any recall. Please refer to our code for details.

**Comment by super-wcg** [comment]
@huiyang865 Did you train your own dataset?How about the detction results?
