### ISSUE TITLE
Usage of NMS

### ISSUE THREAD

**Issue by gudovskiy** [msracver/Relation-Networks-for-Object-Detection#19]
Hi, thanks for your work! I have a question about greedy-NMS usage: do you completely replace NMS with your duplicate removal network or add it complementary to greedy-NMS? From Table 1 it seems that greedy-NMS is still a part of pipeline...

**Comment by chengdazhi** [comment]
No, we don't use greedy-NMS when we use learn nms module. Please refer to the code for details, specifically relation_rcnn/core/tester.py, that's where greedy nms is executed when we don't use learn nms.

**Comment by gudovskiy** [comment]
@chengdazhi thank you!
