### ISSUE TITLE
Training on custom dataset?

### ISSUE THREAD

**Issue by cbsudux** [msracver/Relation-Networks-for-Object-Detection#20]
I'd like to train a Faster R-CNN + Relation module (as in the readme with coco) on my own dataset. How do I go about it?

**Comment by matt-teng** [comment]
So, did you successfully train this module on your own dataset?

**Comment by cbsudux** [comment]
Yeah, just convert into coco format and plug and play : https://github.com/cocodataset/cocoapi/issues/144

**Comment by matt-teng** [comment]
> Yeah, just convert into coco format and plug and play : [cocodataset/cocoapi#144](https://github.com/cocodataset/cocoapi/issues/144)

Thank you
