### ISSUE TITLE
Can not download any models?

### ISSUE THREAD

**Issue by dajiangxiaoyan** [msracver/Relation-Networks-for-Object-Detection#21]
Thanks for sharing the code. Nice work.
I can not open any link of onedirve. They all show:
![image](https://user-images.githubusercontent.com/17979833/42615689-ea62133e-85dd-11e8-8428-765cafb349ef.png)

**Comment by chengdazhi** [comment]
I can still open it, please check if it's your network's problem?

**Comment by dajiangxiaoyan** [comment]
It works! Thanks a lot.
