### ISSUE TITLE
Question about "nongt_dim"

### ISSUE THREAD

**Issue by interstate50** [msracver/Relation-Networks-for-Object-Detection#35]
I don't know what the meaning of "nongt_dim" is in _extract_position_embedding_ and _attention_module_embedding_. If it means "the number of rois that are not ground truth", how to determine which roi is not ground truth during training. Maybe I misunderstand it. Could anyone help me?

**Comment by lilichu** [comment]
hi! do you know how 'nongt_dim' works?
https://github.com/msracver/Relation-Networks-for-Object-Detection/blob/e83e911d828e3c86624ce0aeb8d742d5ee67d5ba/relation_rcnn/symbols/resnet_v1_101_rcnn_attention_1024_pairwise_position_multi_head_16_learn_nms.py#L85
for example, nongt_dim = 2000(rois per image), when train, there is 2 images per batch, so 2000*2 rois. it will get the relation between every rois and first 2000 rois. but the rois of 2th image also get the relation about rois of 1th image.  it is unreasonable.
