### ISSUE TITLE
How to generate "previously proposals"  for another dataset beyond COCO to train  with RPN

### ISSUE THREAD

**Issue by insigh** [msracver/Relation-Networks-for-Object-Detection#38]
Hello,  I am chaojie from Renmin University of China, Beijing.
Thanks for you excellent work in object detection. 
But i have a problem when i try it with my own data,
It is all good for rcnn_attention and rcnn_dcn training and test, but when it comes rcnn_fpn symbol,
**I have to provide the previously generated proposals in the directory like this "./proposal/resnet_v1_101_fpn/rpn_data/{}_{}_rpn.pkl"**,  so could you please give tips to me about how to generate this file for another data with annotations like COCO. I am dying to know it, thank you very much!

**Comment by shenyunlong** [comment]
@chengdazhi

**Comment by insigh** [comment]
@shenyunlong  maybe we should add the function **generate_proposals**(within core.tester) in **test_rcnn.py**, i am trying to fix it. we can know the result in four hours.

**Comment by shenyunlong** [comment]
@insigh 👍 come on!

**Comment by insigh** [comment]
wo should **first train_rpn then test_rpn when we test_rpn we can modify the test file as train/val/test.**
then we can get the proposal cache at ./cache/rpn_data/{}_{}_rpn.pkl. :cn:

**Comment by insigh** [comment]
@shenyunlong :arrow_up:

**Comment by shenyunlong** [comment]
@insigh Good Job 👍
