### ISSUE TITLE
Is it essential to exclude groundtruth box when training with relation module?

### ISSUE THREAD

**Issue by Gus-Guo** [msracver/Relation-Networks-for-Object-Detection#4]
Is it essential to exclude groundtruth box when training with relation module?And why?

**Comment by chengdazhi** [comment]
Yes, because relation modules operate on a pair basis, and is therefore more sensitive to input distribution. If ground truth are provided in training phase, it introduces a gap on input distribution between training and testing, as ground truth boxes are unavailable in testing.

**Comment by Gus-Guo** [comment]
Thank you very much.

**Comment by chengdazhi** [comment]
Glad to help. Still it is encouraged to try it yourself.
