### ISSUE TITLE
mAP Issue

### ISSUE THREAD

**Issue by FrankCAN** [msracver/Relation-Networks-for-Object-Detection#8]
There are several mAP in the paper, for example mAP@0.5, mAP@0.75, mAP@S, does any one know that what does it mean? Is it mean average precision, but if so, does it so low for the detection result? Because the mAP for the faster RCNN is more than 70%, but the best result for this paper is just around 50%. So I think it has different meaning. Many thanks.

**Comment by chengdazhi** [comment]
mAP means exactly mean average precision. It varies on different datasets. The 70% mAP you mentioned is probably evaluated on VOC dataset. I suggest you read the original papers that introduced these datasets, the evaluation metrics are elaborated in detail.
