### ISSUE TITLE
cannot run scirpt due to package compatibility

### ISSUE THREAD

**Issue by chrisliu54** [msracver/Relation-Networks-for-Object-Detection#9]
Hi, I have prepared all the data/pretrained model/environment setting, then I run the command below:
`
python experiments\relation_rcnn\rcnn_end2end_train_test.py --cfg experiments/relation_rcnn/cfgs/resnet_v1_101_coco_trainvalminus_rcnn_end2end_relation_learn_nms_8epoch.yamllminus_rcnn_end2end_relation_learn_nms_8epoch.yaml
`
However, I got the error message below:
![image](https://user-images.githubusercontent.com/12222396/41670832-e7438568-74e7-11e8-9e44-13459bd44035.png)

After I uninstalled and reinstalled `numpy`, it turned to be wrong with `skimage`.

**Comment by super-wcg** [comment]
@chrisliu54 did you solve the problem? I have the same problem as you

**Comment by chrisliu54** [comment]
After I reinstalled numpy=1.14.0 and skimage=0.13.1, the environment(python=2.7) seemed to go well.

**Comment by lingprince** [comment]
I have the same problems with you, how do you solve it?
